"use client";

import { ImagePlaceholder } from "@/components/ImagePlaceholder";
import { boardSectionLabels, getBoardErrors, getBoardProgress, isValidHex, requiredBoardSections } from "@/services/boardUtils";
import type { BoardSectionId, Session } from "@/types";

export function FinalReviewSummary({ session, onEdit, onSubmit }: { session: Session; onEdit: (section: BoardSectionId) => void; onSubmit: () => void }) {
  const { board, images } = session;
  const progress = getBoardProgress(board);
  const errors = getBoardErrors(board);
  const logo = images.find((image) => image.id === board.selectedLogoImageId);
  const visuals = images.filter((image) => board.selectedVisualImageIds.includes(image.id));
  const editLabels: Record<BoardSectionId, string> = { concept: "Edit concept", keywords: "Edit keywords", personality: "Edit personality", audience: "Edit audience", palette: "Edit palette", typography: "Edit typography", logo: "Edit logo / symbol", visuals: "Edit visual style references", tone: "Edit tone of voice", principles: "Edit visual do’s and don’ts", rationale: "Edit rationale" };
  const edit = (section: BoardSectionId) => <button className="reviewEdit" onClick={() => onEdit(section)}>{editLabels[section]}</button>;
  return <section className="finalReviewBoard">
    <header className="reviewTitle"><div><p className="eyebrow">FINAL REVIEW</p><h1>Elsewhere early brand direction</h1><p>Review the direction as one connected system before submitting.</p></div><div className="reviewProgress"><span>Required sections complete <strong>{progress.requiredComplete} / 8</strong></span><span>Supporting sections complete <strong>{progress.supportingComplete} / 3</strong></span></div></header>
    {errors.length > 0 && <div className="reviewNeeded" role="status"><div><strong>Complete before submission</strong><p>{progress.requiredComplete} of 8 required sections are ready.</p></div><ul>{requiredBoardSections.filter((section) => !progress.completion[section]).map((section) => <li key={section}><button onClick={() => onEdit(section)}>{boardSectionLabels[section]} <span>Still needed →</span></button></li>)}</ul></div>}
    <div className="reviewEditorialGrid">
      <article className="reviewConcept"><header><span>01 · Core idea</span><div className="reviewEditGroup">{edit("concept")}{edit("keywords")}</div></header><blockquote>{board.concept || "Brand concept not yet added."}</blockquote><div className="reviewChips">{board.keywords.filter(Boolean).map((keyword) => <span key={keyword}>{keyword}</span>)}</div></article>
      <article><header><span>02 · Personality and audience</span><div className="reviewEditGroup">{edit("personality")}{edit("audience")}</div></header><div className="reviewChips quiet">{board.personalityTraits.map((trait) => <span key={trait}>{trait}</span>)}</div><h3>Audience</h3><p>{board.audienceDescription || "Not yet added"}</p><dl><div><dt>Core need</dt><dd>{board.audienceCoreNeed || "—"}</dd></div><div><dt>Desired response</dt><dd>{board.audienceEmotionalResponse || "—"}</dd></div></dl></article>
      <article className="reviewPalette"><header><span>03 · Colour system</span>{edit("palette")}</header><div>{[["Primary", board.primaryColour], ["Secondary 01", board.secondaryColour1], ["Secondary 02", board.secondaryColour2], ["Accent", board.accentColour]].map(([label, hex]) => <figure className={isValidHex(hex) ? "" : "empty"} key={label}><i style={isValidHex(hex) ? { background: hex } : undefined} /><figcaption><span>{label}</span><strong>{isValidHex(hex) ? hex : "Not set"}</strong></figcaption></figure>)}</div><p>{board.paletteRationale}</p></article>
      <article className={`reviewMedia ${progress.completion.logo ? "reviewComplete" : "reviewIncomplete"}`}><header><span>04 · Logo / symbol</span><div className="reviewFieldActions"><small>{progress.completion.logo ? "Completed ✓" : "Still needed"}</small>{edit("logo")}</div></header>{logo ? <><ImagePlaceholder image={logo} /><strong>{logo.id} · {logo.label}</strong><p>{board.logoDirectionNote || "Direction note not yet added."}</p></> : <p>Not yet selected</p>}</article>
      <article className={`reviewMedia reviewVisuals ${progress.completion.visuals ? "reviewComplete" : "reviewIncomplete"}`}><header><span>05 · Visual references</span><div className="reviewFieldActions"><small>{progress.completion.visuals ? "Completed ✓" : "Still needed"}</small>{edit("visuals")}</div></header><div>{visuals.map((image) => <figure key={image.id}><ImagePlaceholder image={image} compact /><figcaption>{image.id}<span>{board.visualReferenceNotes[image.id] || "Direction note not yet added."}</span></figcaption></figure>)}</div>{!visuals.length && <p>Not yet selected</p>}</article>
      <article className="reviewSupporting"><header><span>Supporting directions</span><div className="reviewEditGroup">{edit("typography")}{edit("tone")}{edit("principles")}</div></header><div><section><h3>Typography</h3><p>{board.primaryTypeStyle || "Not provided"}{board.secondaryTypeStyle ? ` + ${board.secondaryTypeStyle}` : ""}</p><small>{board.typographyMood.join(" · ")}</small></section><section><h3>Tone of voice</h3><p>{board.toneTraits.join(" · ") || "Not provided"}</p><blockquote>{board.sampleLine}</blockquote></section><section><h3>Visual principles</h3><div className="reviewPrinciples"><ul>{board.visualDos.filter(Boolean).map((item) => <li key={item}>Do · {item}</li>)}</ul><ul>{board.visualDonts.filter(Boolean).map((item) => <li key={item}>Don’t · {item}</li>)}</ul></div></section></div></article>
      <article className="reviewRationale"><header><span>06 · Final rationale</span>{edit("rationale")}</header><p>{board.rationale || "Final rationale not yet added."}</p></article>
    </div>
    <footer className="reviewSubmit"><div><span>Required direction</span><strong>{progress.requiredComplete === 8 ? "Ready to submit" : `${8 - progress.requiredComplete} required ${8 - progress.requiredComplete === 1 ? "section" : "sections"} still needed`}</strong><p>Submission locks the participant workspace. A researcher can restart the session if required.</p></div><button className="primaryButton" disabled={errors.length > 0} onClick={onSubmit}>Submit final direction →</button></footer>
  </section>;
}
