"use client";

import { useState } from "react";
import { calibrationStorageAdapter } from "@/services/calibrationStorageAdapter";
import { buildAtomicCodingCsv, buildCalibrationJson, buildMessageCodingCsv, buildPilotCalibrationSummary, createFreezeRecord, freezeClassifierRecord } from "@/services/pilotCodingService";
import { DECISION_TRACE_PROMPT_VERSION } from "@/services/decisionTraceClassifier";
import type { CalibrationDecision, CalibrationWorkspaceRecord, ClassifierFreezeRecord, Session } from "@/types";

function download(filename: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function PilotCalibrationWorkspace({ sessions }: { sessions: Session[] }) {
  const [workspace, setWorkspace] = useState<CalibrationWorkspaceRecord>(() => calibrationStorageAdapter.load());
  const [issue, setIssue] = useState(""); const [messageIds, setMessageIds] = useState(""); const [adjustment, setAdjustment] = useState(""); const [rationale, setRationale] = useState(""); const [implementationVersion, setImplementationVersion] = useState(""); const [decision, setDecision] = useState<CalibrationDecision>("deferred");
  const [appVersion, setAppVersion] = useState(""); const [modelId, setModelId] = useState(""); const [freezeRationale, setFreezeRationale] = useState("");
  const summary = buildPilotCalibrationSummary(sessions);
  const frozen = workspace.freezeRecords.findLast((record) => record.status === "frozen");
  const save = (next: CalibrationWorkspaceRecord) => { setWorkspace(next); calibrationStorageAdapter.save(next); };
  const addLog = () => {
    if (!issue.trim() || !adjustment.trim() || !rationale.trim()) return;
    save({ ...workspace, calibrationLog: [...workspace.calibrationLog, { id: `CAL-LOG-${Date.now()}`, date: new Date().toISOString(), classifierPromptVersion: DECISION_TRACE_PROMPT_VERSION, observedIssue: issue.trim(), representativeMessageIds: messageIds.split(/[,\s]+/).filter(Boolean), proposedRuleAdjustment: adjustment.trim(), decision, rationale: rationale.trim(), author: "R01", implementationVersion: implementationVersion.trim() || undefined }] });
    setIssue(""); setMessageIds(""); setAdjustment(""); setRationale(""); setImplementationVersion("");
  };
  const createDraft = () => {
    if (!appVersion.trim() || !modelId.trim() || !freezeRationale.trim()) return;
    const record = createFreezeRecord({ classifierPromptVersion: DECISION_TRACE_PROMPT_VERSION, applicationVersion: appVersion.trim(), geminiModelId: modelId.trim(), confidenceThresholds: "clear ≥ 0.80; needs review 0.65–0.79; uncertain < 0.65", pilotSessionIds: sessions.filter((session) => session.studyStatus === "pilot").map((session) => session.id), rationale: freezeRationale.trim() });
    save({ ...workspace, freezeRecords: [...workspace.freezeRecords, record] });
  };
  const freeze = (record: ClassifierFreezeRecord) => save({ ...workspace, freezeRecords: workspace.freezeRecords.map((item) => item.id === record.id ? freezeClassifierRecord(item, "R01") : item.status === "frozen" ? { ...item, status: "superseded" } : item) });
  const percent = (value: number) => `${Math.round(value * 100)}%`;

  return <section className="calibrationWorkspace">
    <header><div><p className="eyebrow">PILOT VALIDATION</p><h2>Classifier calibration</h2><p>Agreement statistics are descriptive calibration evidence and should be interpreted alongside the underlying messages and coding notes.</p></div><div className="calibrationExports"><button onClick={() => download("pilot-message-coding.csv", buildMessageCodingCsv(sessions), "text/csv;charset=utf-8")}>Message coding CSV</button><button onClick={() => download("pilot-atomic-units.csv", buildAtomicCodingCsv(sessions), "text/csv;charset=utf-8")}>Atomic-unit CSV</button><button onClick={() => download("pilot-calibration.json", buildCalibrationJson(sessions, workspace), "application/json")}>Calibration JSON</button><button onClick={() => download("formal-message-coding.csv", buildMessageCodingCsv(sessions, ["formal"]), "text/csv;charset=utf-8")}>Formal-only CSV</button></div></header>
    {frozen && <div className="freezeWarning"><strong>Classifier version frozen</strong><span>{frozen.classifierPromptVersion} · {frozen.applicationVersion} · {new Date(frozen.freezeTimestamp!).toLocaleString("en-GB")}</span><p>Record any later classifier-related change as a new explicit version. Existing sessions must not be silently reclassified.</p></div>}
    <div className="calibrationMetrics"><div><strong>{summary.totalPilotSessions}</strong><span>Pilot sessions</span></div><div><strong>{summary.totalHumanCodedMessages} / {summary.totalParticipantMessages}</strong><span>Messages coded</span></div><div><strong>{percent(summary.decisionNoDecisionAgreementRate)}</strong><span>Decision / no-decision agreement</span></div><div><strong>{percent(summary.exactCategoryAgreementRate)}</strong><span>Exact category agreement</span></div><div><strong>{percent(summary.uncertainRate)}</strong><span>Uncertain rate</span></div><div><strong>{summary.messagesRequiringAdjudication}</strong><span>Require adjudication</span></div><div><strong>{summary.automatedFalsePositiveCount}</strong><span>Automated false positives</span></div><div><strong>{summary.automatedFalseNegativeCount}</strong><span>Automated false negatives</span></div></div>
    <details className="confusionDetails"><summary>Category confusion and confidence</summary><div className="confusionGrid">{Object.entries(summary.categoryConfusion).map(([key, value]) => <span key={key}><b>{key}</b>{value}</span>)}</div><p>Average automated confidence: agreements {summary.averageAutomatedConfidenceForAgreements?.toFixed(2) ?? "—"}; disagreements {summary.averageAutomatedConfidenceForDisagreements?.toFixed(2) ?? "—"}.</p>{summary.coderAgreement && <p>Coder 1 / coder 2: message agreement {percent(summary.coderAgreement.messageLevelAgreementRate)}; category agreement {percent(summary.coderAgreement.categoryAgreementRate)}; {summary.coderAgreement.disagreementCount} disagreements ({percent(summary.coderAgreement.disagreementProportion)}).</p>}</details>
    <div className="calibrationColumns"><section><h3>Classifier calibration log</h3><div className="calibrationForm"><label>Observed issue<textarea value={issue} onChange={(event) => setIssue(event.target.value)} /></label><label>Representative anonymised message IDs<input value={messageIds} onChange={(event) => setMessageIds(event.target.value)} /></label><label>Proposed rule adjustment<textarea value={adjustment} onChange={(event) => setAdjustment(event.target.value)} /></label><label>Decision<select value={decision} onChange={(event) => setDecision(event.target.value as CalibrationDecision)}><option>accepted</option><option>rejected</option><option>deferred</option></select></label><label>Implementation version, if changed<input value={implementationVersion} onChange={(event) => setImplementationVersion(event.target.value)} /></label><label>Rationale<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} /></label><button onClick={addLog}>Add calibration entry</button></div><div className="calibrationLog">{workspace.calibrationLog.map((entry) => <article key={entry.id}><strong>{entry.decision} · {entry.classifierPromptVersion}</strong><span>{new Date(entry.date).toLocaleDateString("en-GB")} · {entry.author}{entry.implementationVersion ? ` · implemented ${entry.implementationVersion}` : ""}</span><p>{entry.observedIssue}</p><small>{entry.proposedRuleAdjustment} · {entry.rationale}</small></article>)}</div></section>
      <section><h3>Classifier freeze record</h3><div className="calibrationForm"><label>Application version / commit<input value={appVersion} onChange={(event) => setAppVersion(event.target.value)} /></label><label>Gemini model ID<input value={modelId} onChange={(event) => setModelId(event.target.value)} /></label><label>Freeze rationale<textarea value={freezeRationale} onChange={(event) => setFreezeRationale(event.target.value)} /></label><button onClick={createDraft}>Create draft freeze record</button></div><div className="calibrationLog">{workspace.freezeRecords.map((record) => <article key={record.id}><strong>{record.status} · {record.classifierPromptVersion}</strong><span>{record.applicationVersion} · {record.geminiModelId}</span><p>{record.rationale}</p><small>{record.pilotSessionIds.length} pilot sessions · {record.confidenceThresholds}</small>{record.status === "draft" && <button onClick={() => freeze(record)}>Mark frozen</button>}</article>)}</div></section></div>
  </section>;
}
