"use client";

import { useState } from "react";
import { ImagePlaceholder } from "@/components/ImagePlaceholder";
import { ResearcherAIConfigPanel } from "@/components/ResearcherAIConfigPanel";
import { PilotCodingPanel } from "@/components/PilotCodingPanel";
import { getBoardProgress } from "@/services/boardUtils";
import { buildDecisionsCsv, buildSessionJson, buildSessionSummaryCsv } from "@/services/exportService";
import { getPreAiRecordStatus } from "@/services/preAiStartingPoint";
import { auditSessionIntegrity } from "@/services/researchDataAudit";
import type { DecisionAction, DecisionCategory, DecisionObject, DecisionSource, DecisionUnit, Session } from "@/types";

interface Props { session: Session; sessions?: Session[]; onChange: (session: Session) => void; }
const objects: DecisionObject[] = ["Brand concept", "Keywords", "Brand personality", "Audience interpretation", "Colour palette", "Typography", "Logo or symbol", "Visual style", "Tone of voice", "Visual principles", "Prompt or constraint", "Final selection", "Other"];
const categories: DecisionCategory[] = ["accept", "modify", "reject", "human_initiated", "uncertain"];
const reviewedAction: Record<DecisionCategory, DecisionAction> = { accept: "Accept", modify: "Modify", reject: "Reject", human_initiated: "Human-initiated", uncertain: "Uncertain" };
const reviewedSource: Record<DecisionCategory, DecisionSource> = { accept: "AI-initiated", modify: "Mixed", reject: "AI-initiated", human_initiated: "Human-initiated", uncertain: "Unclear" };

function download(filename: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.hidden = true;
  document.body.appendChild(anchor); anchor.click(); anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
const sourceLabel = (turn: number | null) => turn && turn > 0 ? `Turn ${String(turn).padStart(2, "0")}` : "Board";

export function ResearcherView({ session, sessions = [], onChange }: Props) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [codingMode, setCodingMode] = useState(false);
  const boardProgress = getBoardProgress(session.board);
  const reviewedCount = session.decisions.filter((decision) => decision.reviewStatus !== "Unreviewed").length;
  const imageRequestsSucceeded = session.imageRequests.filter((request) => request.status === "succeeded").length || session.imageRequestCount;
  const imageRequestsFailed = session.imageRequests.filter((request) => request.status === "failed").length;
  const imagesUsed = session.images.filter((image) => (image.usageTargets?.length ?? 0) > 0).length;
  const suggestedEvent = session.researchEvents.find((event) => event.type === "suggested_time_reached");
  const finalReviewEvent = session.researchEvents.find((event) => event.type === "final_review_opened");
  const preAiStatus = getPreAiRecordStatus(session);
  const preAi = session.preAiStartingPoint;
  const diagnosticTextRequests = session.aiTextRequests.filter((request) => request.status === "failed" || (request.attemptCount ?? request.attempts?.length ?? 1) > 1);
  const integrityAudit = auditSessionIntegrity(session);
  const actualElapsed = session.completionTimeSeconds ?? (session.participantStartedAt && (session.endedAt || session.submittedAt) ? Math.max(0, Math.floor((new Date(session.endedAt ?? session.submittedAt!).getTime() - new Date(session.participantStartedAt).getTime()) / 1000)) : undefined);
  const sessionById = new Map(sessions.map((item) => [item.id, item]));
  const rootAttemptId = (item: Session) => {
    let current = item;
    const visited = new Set<string>();
    while (current.previousAttemptId && !visited.has(current.id)) {
      visited.add(current.id);
      const previous = sessionById.get(current.previousAttemptId);
      if (!previous) break;
      current = previous;
    }
    return current.id;
  };
  const currentRootId = rootAttemptId(session);
  const relatedAttempts = sessions.filter((item) => rootAttemptId(item) === currentRootId).sort((a, b) => a.attemptNumber - b.attemptNumber);
  const messageById = new Map(session.messages.map((message) => [message.id, message]));
  const propositionById = new Map((session.aiPropositions ?? []).map((proposition) => [proposition.id, proposition]));
  const updateDecision = (id: string, patch: Partial<DecisionUnit>) => onChange({ ...session, decisions: session.decisions.map((decision) => decision.id === id ? { ...decision, ...patch } : decision) });
  const reviewPatch = (decision: DecisionUnit, category: DecisionCategory | null, note?: string): Partial<DecisionUnit> => {
    const action = category ? reviewedAction[category] : decision.action;
    const source = category ? reviewedSource[category] : decision.source;
    return {
      reviewStatus: category === decision.originalModelCategory ? "Confirmed" : "Corrected",
      currentReviewedCategory: category,
      finalReviewedLabel: { action, source, object: decision.object, summary: decision.summary },
      reviewedAt: new Date().toISOString(), reviewerId: session.researcherId, reviewNote: note,
    };
  };
  const changeCategory = (decision: DecisionUnit, category: DecisionCategory) => updateDecision(decision.id, {
    action: reviewedAction[category], source: reviewedSource[category], currentReviewedCategory: category,
  });
  const correct = (decision: DecisionUnit) => { updateDecision(decision.id, { ...reviewPatch(decision, decision.currentReviewedCategory ?? decision.category ?? null), reviewStatus: "Corrected" }); setEditingId(null); };
  const nextDecisionNumber = () => Math.max(0, ...session.decisions.map((decision) => Number(decision.id.replace(/\D/g, ""))).filter(Number.isFinite)) + 1;
  const splitUnit = (decision: DecisionUnit) => {
    const parts = (decision.evidenceText ?? decision.summary).split(/\s*(?:,|;|，|；|\bbut\b|\band\b|但是|但)\s*/i).filter((part) => part.trim().length > 3).slice(0, 2);
    if (parts.length < 2) return;
    const first = nextDecisionNumber();
    const children = parts.map((part, index): DecisionUnit => ({
      ...decision,
      id: `D${String(first + index).padStart(2, "0")}`,
      summary: part.trim(), evidenceText: part.trim(),
      finalReviewedLabel: { ...decision.finalReviewedLabel, summary: part.trim() },
      reviewStatus: "Corrected", reviewedAt: new Date().toISOString(), reviewerId: session.researcherId,
      reviewNote: `Split from ${decision.id}.`, idempotencyKey: `${decision.idempotencyKey ?? decision.id}-split-${index + 1}`,
    }));
    onChange({ ...session, decisions: [...session.decisions.map((item) => item.id === decision.id ? { ...item, ...reviewPatch(item, null, `Split into ${children.map((child) => child.id).join(" and ")}.`) } : item), ...children] });
  };
  const mergeWithPrevious = (decision: DecisionUnit) => {
    const key = [...(decision.linkedAiPropositionIds ?? [])].sort().join("|");
    if (!key) return;
    const previous = [...session.decisions].reverse().find((item) => item.id !== decision.id && [...(item.linkedAiPropositionIds ?? [])].sort().join("|") === key && item.currentReviewedCategory !== null);
    if (!previous) return;
    const id = `D${String(nextDecisionNumber()).padStart(2, "0")}`;
    const merged: DecisionUnit = {
      ...decision, id, summary: `${previous.summary}; ${decision.summary}`, evidenceText: `${previous.evidenceText ?? ""} ${decision.evidenceText ?? ""}`.trim(),
      finalReviewedLabel: { ...decision.finalReviewedLabel, summary: `${previous.summary}; ${decision.summary}` },
      reviewStatus: "Corrected", reviewedAt: new Date().toISOString(), reviewerId: session.researcherId,
      reviewNote: `Merged from ${previous.id} and ${decision.id}.`, idempotencyKey: `merge-${previous.id}-${decision.id}`,
    };
    onChange({ ...session, decisions: [...session.decisions.map((item) => item.id === previous.id || item.id === decision.id ? { ...item, ...reviewPatch(item, null, `Merged into ${id}.`) } : item), merged] });
  };
  const exportCsv = () => {
    download(`${session.participantId}-decisions.csv`, buildDecisionsCsv(session), "text/csv;charset=utf-8");
  };

  if (codingMode) return <main className="researcherView blindedCodingView"><header className="researcherTitle"><div><p className="eyebrow">BLINDED CODING</p><h1>Pilot message coding</h1><p>Condition, automated labels and participant identity are withheld from the coding workspace by default.</p></div><button type="button" onClick={() => setCodingMode(false)}>Return to session record</button></header><PilotCodingPanel session={session} onChange={onChange} /></main>;

  return <main className="researcherView">
    <header className="researcherTitle"><div><p className="eyebrow">PRIVATE RESEARCHER VIEW</p><h1>Session record</h1><p>Model outputs, board interaction events and reviewed labels are retained separately.</p></div><div className="exportActions"><button onClick={() => download(`${session.participantId}-session.json`, buildSessionJson(session), "application/json")}>Export JSON</button><button onClick={() => download(`${session.participantId}-summary.csv`, buildSessionSummaryCsv(session), "text/csv;charset=utf-8")}>Export summary CSV</button><button onClick={exportCsv}>Export decisions CSV</button></div></header>
    <section className="metadataGrid"><div><span>Participant / attempt</span><strong>{session.participantId} · {session.attemptNumber}</strong></div><div><span>Condition</span><strong>Condition {session.condition}</strong></div><div><span>Researcher</span><strong>{session.researcherId}</strong></div><div><span>Date / duration</span><strong>{session.sessionDate} · {session.taskDurationMinutes} min</strong></div><div><span>Board</span><strong>{boardProgress.requiredComplete} / 8 required · {boardProgress.supportingComplete} / 3 supporting</strong></div><div><span>Status / session</span><strong>{session.status} · {session.id}</strong></div><div><span>Study status</span><strong>{(session.studyStatus ?? "development_test").replaceAll("_", " ")}</strong></div><div><span>Assignment</span><strong>{session.assignmentMethod === "researcher_manual" ? "Researcher manual" : session.assignmentMethod === "balanced_random" ? "Balanced random" : "Historical session"}</strong></div><div><span>Assignment time</span><strong>{session.assignmentTimestamp ? new Date(session.assignmentTimestamp).toLocaleString("en-GB") : "—"}</strong></div><div><span>Allocation</span><strong>{session.assignmentBlockId ? `${session.assignmentBlockId} · position ${session.assignmentPosition ?? "—"}` : session.assignmentMethod === "researcher_manual" ? "Manual override" : "—"}</strong></div><div><span>Frozen classifier</span><strong>{session.activeFrozenClassifierVersion ?? "Not assigned"}</strong></div><div><span>Brand brief</span><strong>{session.brandBriefId ?? "Historical session"}</strong></div><div><span>Task guide</span><strong>{session.taskGuideVersion ?? "Historical session"}</strong></div><div><span>Text prompt</span><strong>{session.textPromptVersion ?? "Historical session"}</strong></div><div><span>Image prompt</span><strong>{session.imagePromptVersion ?? "Historical session"}</strong></div></section>
    <ResearcherAIConfigPanel />
    <section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">READ-ONLY AUDIT</p><h2>Record and export consistency</h2></div><span>{integrityAudit.status}</span></div><div className="attemptCounts"><span>{integrityAudit.participantMessages} participant messages</span><span>{integrityAudit.assistantMessages} assistant messages</span><span>{integrityAudit.propositions} propositions</span><span>{integrityAudit.decisionUnits} automatic units</span><span>{integrityAudit.csvDecisionRows} Decision CSV rows</span></div>{integrityAudit.issues.length ? <ul>{integrityAudit.issues.map((issue) => <li key={issue}>{issue}</li>)}</ul> : <p className="emptyNote">UI record, JSON source and Decision CSV counts are internally consistent.</p>}</section>
    <section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">DEVELOPMENT DIAGNOSTICS</p><h2>AI text request attempts</h2></div><span>{diagnosticTextRequests.length} flagged</span></div><div className="traceClassificationList">{diagnosticTextRequests.map((request) => <article key={request.requestId}><strong>{request.status} · Turn {String(request.turn).padStart(2, "0")}</strong><span>{request.requestId}</span><small>{request.attemptCount ?? request.attempts?.length ?? 1} attempts · {request.finalResolution ?? "legacy result"}{request.failureCategory ? ` · ${request.failureCategory}` : ""}{request.errorStage ? ` · ${request.errorStage}` : ""}{request.providerStatusCode ? ` · HTTP ${request.providerStatusCode}` : ""}</small><small>{request.finishReason ? `Finish: ${request.finishReason}` : "No finish reason"} · {request.candidateCount ?? "—"} candidates · input {request.inputTokenCount ?? "—"} / output {request.outputTokenCount ?? "—"} tokens</small>{request.attempts?.map((attempt) => <small key={attempt.attempt}>Attempt {attempt.attempt}: {attempt.status} · {attempt.durationMs} ms{attempt.retryReason ? ` · retry ${attempt.retryReason}` : ""}{attempt.timeout ? " · timeout" : ""}</small>)}{request.safeErrorMessage && <small>{request.safeErrorMessage}</small>}</article>)}{!diagnosticTextRequests.length && <p className="emptyNote">No failed or internally retried AI text requests.</p>}</div></section>

    <section className="researchSection preAiResearchRecord"><div className="researchSectionTitle"><div><p className="eyebrow">PARTICIPANT RECORD</p><h2>Pre-AI starting point</h2></div><span>{preAiStatus}</span></div>{preAi ? <div className="preAiResearchContent"><article><span>Initial interpretation</span><p>{preAi.initialInterpretation || "Not yet entered"}</p></article><article><span>Three starting keywords</span><ol>{preAi.keywords.map((keyword, index) => <li key={index}>{keyword || "Not yet entered"}</li>)}</ol></article><article><span>Initial visual question or direction</span><p>{preAi.visualQuestion || "Not yet entered"}</p></article><dl><div><dt>Started</dt><dd>{preAi.startedAt ? new Date(preAi.startedAt).toLocaleString("en-GB") : "Not started"}</dd></div><div><dt>Submitted</dt><dd>{preAi.submittedAt ? new Date(preAi.submittedAt).toLocaleString("en-GB") : "Not submitted"}</dd></div><div><dt>Duration</dt><dd>{preAi.durationMs === null ? "—" : `${Math.floor(preAi.durationMs / 60000)}m ${Math.floor((preAi.durationMs % 60000) / 1000)}s`}</dd></div></dl></div> : <p className="emptyNote">Not available for legacy session.</p>}</section>

    <section className="researchSection questionnaireResearchRecord"><div className="researchSectionTitle"><div><p className="eyebrow">PARTICIPANT CONFIRMATION</p><h2>Post-task questionnaire status</h2></div><span>{session.postTaskQuestionnaires?.studyCompletedAt ? "Study completed" : session.postTaskQuestionnaires ? "In progress" : "Legacy session"}</span></div>{session.postTaskQuestionnaires ? <dl><div><dt>Main questionnaire required</dt><dd>Yes</dd></div><div><dt>Main questionnaire opened</dt><dd>{session.postTaskQuestionnaires.main.openedAt ? new Date(session.postTaskQuestionnaires.main.openedAt).toLocaleString("en-GB") : "Not opened"}</dd></div><div><dt>Main participant confirmation</dt><dd>{session.postTaskQuestionnaires.main.participantConfirmedSubmitted ? `Confirmed${session.postTaskQuestionnaires.main.confirmedAt ? ` · ${new Date(session.postTaskQuestionnaires.main.confirmedAt).toLocaleString("en-GB")}` : ""}` : "Not confirmed"}</dd></div><div><dt>Additional questionnaire required</dt><dd>{session.postTaskQuestionnaires.additional.required ? "Yes" : "Not required"}</dd></div><div><dt>Additional questionnaire opened</dt><dd>{session.postTaskQuestionnaires.additional.required ? session.postTaskQuestionnaires.additional.openedAt ? new Date(session.postTaskQuestionnaires.additional.openedAt).toLocaleString("en-GB") : "Not opened" : "Not required"}</dd></div><div><dt>Additional participant confirmation</dt><dd>{session.postTaskQuestionnaires.additional.required ? session.postTaskQuestionnaires.additional.participantConfirmedSubmitted ? `Confirmed${session.postTaskQuestionnaires.additional.confirmedAt ? ` · ${new Date(session.postTaskQuestionnaires.additional.confirmedAt).toLocaleString("en-GB")}` : ""}` : "Not confirmed" : "Not required"}</dd></div><div><dt>Study completed</dt><dd>{session.postTaskQuestionnaires.studyCompletedAt ? new Date(session.postTaskQuestionnaires.studyCompletedAt).toLocaleString("en-GB") : "Not completed"}</dd></div></dl> : <p className="emptyNote">Not available for legacy session.</p>}</section>

    <section className="researchSection codingLaunch"><div className="researchSectionTitle"><div><p className="eyebrow">METHOD VALIDATION</p><h2>Pilot coding</h2></div>{session.studyStatus === "pilot" && <button type="button" onClick={() => setCodingMode(true)}>Open blinded coding workspace</button>}</div><p>{session.studyStatus === "pilot" ? "Code participant conversation messages without condition or automated labels visible by default." : "Mark this session as Pilot in Researcher records before adding human calibration coding."}</p></section>

    <section className="researchSection attemptSummary"><div className="researchSectionTitle"><div><p className="eyebrow">ATTEMPT SUMMARY</p><h2>Session timing and record completeness</h2></div><span>Attempt {session.attemptNumber}</span></div><dl><div><dt>Task start</dt><dd>{session.participantStartedAt ? new Date(session.participantStartedAt).toLocaleString("en-GB") : "Not started"}</dd></div><div><dt>Suggested time reached</dt><dd>{session.suggestedTimeReachedAt ? new Date(session.suggestedTimeReachedAt).toLocaleString("en-GB") : suggestedEvent ? new Date(suggestedEvent.createdAt).toLocaleString("en-GB") : "Not reached"}</dd></div><div><dt>Final Review opened</dt><dd>{session.finalReviewOpenedAt ? new Date(session.finalReviewOpenedAt).toLocaleString("en-GB") : finalReviewEvent ? new Date(finalReviewEvent.createdAt).toLocaleString("en-GB") : "Not opened"}</dd></div><div><dt>Submission</dt><dd>{session.submittedAt ? new Date(session.submittedAt).toLocaleString("en-GB") : "Not submitted"}</dd></div><div><dt>Actual elapsed</dt><dd>{actualElapsed === undefined ? "—" : `${Math.floor(actualElapsed / 60)}m ${actualElapsed % 60}s`}</dd></div><div><dt>End reason</dt><dd>{session.endReason?.replaceAll("_", " ") ?? "—"}</dd></div><div><dt>Participant messages</dt><dd>{session.messages.filter((message) => message.role === "participant").length}</dd></div><div><dt>AI text requests</dt><dd>{session.aiTextRequests.filter((request) => request.status === "succeeded").length} succeeded · {session.aiTextRequests.filter((request) => request.status === "failed").length} failed</dd></div><div><dt>Image requests</dt><dd>{imageRequestsSucceeded} succeeded · {imageRequestsFailed} failed</dd></div><div><dt>Generated / used images</dt><dd>{session.images.length} generated · {imagesUsed} used</dd></div><div><dt>Board events</dt><dd>{session.boardEvents.length}</dd></div><div><dt>Decision Units</dt><dd>{session.decisions.length}</dd></div><div><dt>Decision review</dt><dd>{reviewedCount} reviewed · {session.decisions.length - reviewedCount} unreviewed</dd></div><div><dt>Final submission</dt><dd>{session.finalSubmission ? "Immutable snapshot saved" : "No snapshot"}</dd></div></dl>{relatedAttempts.length > 1 && <nav aria-label="Participant attempts">{relatedAttempts.map((attempt) => <a className={attempt.id === session.id ? "active" : ""} key={attempt.id} href={`/researcher/session/${attempt.id}`}>Attempt {attempt.attemptNumber} · {attempt.status}</a>)}</nav>}</section>

    <section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">DECISION DATA</p><h2>Text-conversation Decision Units</h2></div><span>{session.decisions.length} units · {(session.traceClassifications ?? []).length} classifications</span></div>
      {(session.traceClassifications ?? []).length > 0 && <div className="traceClassificationList">{(session.traceClassifications ?? []).map((record) => <article key={record.requestId}><strong>{record.status.replaceAll("TRACE_", "").replaceAll("_", " ")}</strong><span>{record.participantMessageId} · {record.classifierPromptVersion}</span><small>{record.provider ?? "Pending"}{record.modelId ? ` · ${record.modelId}` : ""}{typeof record.latencyMs === "number" ? ` · ${record.latencyMs} ms` : ""} · {record.unitIds.length} units</small><small>{record.attemptCount ?? (record.completedAt ? 1 : 0)} attempts · {record.finalResolution ?? "legacy / pending"}{record.errorStage && record.errorStage !== "none" ? ` · ${record.errorStage}` : ""}{record.providerStatusCode ? ` · HTTP ${record.providerStatusCode}` : ""}</small><small>Propositions: {record.extractionStatus ?? "legacy"} · {record.extractionAttemptCount ?? 0} extraction attempts</small>{record.segmentationStatus && <small>Segmentation: {record.segmentationStatus} · {record.segmentationEvidence?.length ?? 0} candidates{record.segmentationOverflow ? " · overflow requires review" : ""}</small>}{record.candidateOutcomes?.map((outcome) => <small key={outcome.candidateId}>Candidate {outcome.candidateId.split(":").at(-1)}: {outcome.status} · {outcome.attemptCount} attempts{outcome.errorStage ? ` · ${outcome.errorStage}` : ""}{outcome.validationPath ? ` · ${outcome.validationPath}` : ""} · “{outcome.evidenceText}”</small>)}</article>)}</div>}
      <div className="decisionTableWrap"><table className="decisionTable"><thead><tr><th>ID / time</th><th>Current category</th><th>Summary and evidence</th><th>Linked context</th><th>Confidence / status</th><th>Review</th><th>Actions</th></tr></thead><tbody>
      {session.decisions.map((decision) => {
        const category = decision.currentReviewedCategory ?? decision.category;
        const linkedMessages = (decision.linkedAiMessageIds ?? []).map((id) => messageById.get(id)).filter(Boolean);
        const linkedPropositions = (decision.linkedAiPropositionIds ?? []).map((id) => propositionById.get(id)).filter(Boolean);
        const canMerge = (decision.linkedAiPropositionIds?.length ?? 0) > 0 && session.decisions.some((item) => item.id !== decision.id && [...(item.linkedAiPropositionIds ?? [])].sort().join("|") === [...(decision.linkedAiPropositionIds ?? [])].sort().join("|") && item.currentReviewedCategory !== null);
        return <tr key={decision.id}>
          <td><strong>{decision.id}</strong><small>{Math.floor(decision.timestampSeconds / 60)}m {decision.timestampSeconds % 60}s<br />{decision.classifiedAt ? new Date(decision.classifiedAt).toLocaleString("en-GB") : sourceLabel(decision.relatedTurn)}</small></td>
          <td>{editingId === decision.id ? <div className="editStack"><select aria-label={`Category for ${decision.id}`} value={category ?? "uncertain"} onChange={(event) => changeCategory(decision, event.target.value as DecisionCategory)}>{categories.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><select value={decision.object} onChange={(event) => updateDecision(decision.id, { object: event.target.value as DecisionObject })}>{objects.map((item) => <option key={item}>{item}</option>)}</select></div> : <><strong>{category?.replaceAll("_", " ") ?? "no decision"}</strong><small>{decision.source} · {decision.object}</small></>}</td>
          <td>{editingId === decision.id ? <textarea aria-label={`Neutral summary for ${decision.id}`} value={decision.summary} onChange={(event) => updateDecision(decision.id, { summary: event.target.value, finalReviewedLabel: { ...decision.finalReviewedLabel, summary: event.target.value } })} /> : <><p>{decision.summary}</p>{decision.evidenceText && <blockquote>“{decision.evidenceText}”</blockquote>}</>}<details><summary>Original automated result</summary><p>{decision.originalModelCategory ?? decision.originalModelLabel.action} · {decision.originalModelLabel.object}<br />{decision.originalModelLabel.summary}</p></details></td>
          <td><span>{sourceLabel(decision.relatedTurn)}</span><small>Source status: {decision.sourceStatus?.replaceAll("_", " ") ?? "Legacy"}</small>{decision.sourceMatchDiagnostics && <small>Matcher: {decision.sourceMatchDiagnostics.matcherRule.replaceAll("_", " ")} · score {decision.sourceMatchDiagnostics.similarityScore.toFixed(2)}{decision.sourceMatchDiagnostics.meaningfulMatchedTokens.length ? ` · tokens ${decision.sourceMatchDiagnostics.meaningfulMatchedTokens.join(", ")}` : ""}{decision.sourceMatchDiagnostics.rejectedWeakMatchReason ? ` · rejected ${decision.sourceMatchDiagnostics.rejectedWeakMatchReason.replaceAll("_", " ")}` : ""}{decision.sourceMatchDiagnostics.matchedExcerpt ? ` · excerpt “${decision.sourceMatchDiagnostics.matchedExcerpt.slice(0, 180)}”` : ""}</small>}{linkedMessages.map((message) => <small key={message!.id}>AI {message!.id}: {message!.content.slice(0, 180)}</small>)}{linkedPropositions.map((proposition) => <small key={proposition!.id}>{proposition!.id}: {proposition!.summary}</small>)}{decision.reversesDecisionUnitId && <small>Reverses {decision.reversesDecisionUnitId}</small>}{decision.supersedesDecisionUnitId && <small>Supersedes {decision.supersedesDecisionUnitId}</small>}</td>
          <td><span className={`confidence ${decision.confidence.toLowerCase()}`}>{typeof decision.confidenceScore === "number" ? decision.confidenceScore.toFixed(2) : decision.confidence}</span><small>{decision.reasonCode ?? "Legacy label"}<br />{decision.classifierStatus ?? "Legacy record"}</small></td>
          <td><span className={`review ${decision.reviewStatus.toLowerCase()}`}>{decision.reviewStatus}</span>{decision.reviewedAt && <small>{new Date(decision.reviewedAt).toLocaleString("en-GB")} · {decision.reviewerId}</small>}{decision.reviewNote && <small>{decision.reviewNote}</small>}</td>
          <td><div className="tableActions">{editingId === decision.id ? <button onClick={() => correct(decision)}>Save correction</button> : <><button onClick={() => updateDecision(decision.id, reviewPatch(decision, decision.category ?? decision.currentReviewedCategory ?? null))}>Confirm</button><button onClick={() => setEditingId(decision.id)}>Change / edit</button></>}<button onClick={() => updateDecision(decision.id, reviewPatch(decision, "uncertain"))}>Mark uncertain</button><button onClick={() => updateDecision(decision.id, reviewPatch(decision, null, "Marked as no decision."))}>Mark no decision</button><button onClick={() => splitUnit(decision)} disabled={!/[;,，；]|\b(?:but|and)\b|但是|但/i.test(decision.evidenceText ?? decision.summary)}>Split unit</button><button onClick={() => mergeWithPrevious(decision)} disabled={!canMerge}>Merge related</button></div></td>
        </tr>;
      })}{!session.decisions.length && <tr><td colSpan={7}>No Decision Units recorded.</td></tr>}
    </tbody></table></div></section>

    <section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">DIRECT BOARD ACTIVITY</p><h2>Board interaction history</h2></div><span>{session.boardEvents.length} events</span></div><div className="boardEventList">{[...session.boardEvents].reverse().map((event) => <article key={event.id}><strong>{event.id}</strong><span>{event.object}</span><p>{event.summary}</p><small>{Math.floor(event.timestampSeconds / 60)}m {event.timestampSeconds % 60}s · {event.eventType?.replaceAll("_", " ") ?? event.action}{event.relatedImageId ? ` · ${event.relatedImageId}` : ""}</small></article>)}{!session.boardEvents.length && <p className="emptyNote">No direct board interactions recorded yet.</p>}</div></section>

    <section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">SESSION EVENTS</p><h2>Protocol and navigation history</h2></div><span>{session.researchEvents.length} events</span></div><div className="researchEventList">{[...session.researchEvents].reverse().map((event) => <article key={event.id}><strong>{event.id}</strong><span>{event.type.replaceAll("_", " ")}</span><p>{event.summary}</p><small>{event.actor} · {Math.floor(event.timestampSeconds / 60)}m {event.timestampSeconds % 60}s{event.requestId ? ` · ${event.requestId}` : ""}{event.failureCategory ? ` · ${event.failureCategory}` : ""}</small></article>)}{!session.researchEvents.length && <p className="emptyNote">No protocol events recorded yet.</p>}</div></section>

    <div className="researchTwoCol"><section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">FULL RECORD</p><h2>Chat transcript</h2></div><span>{session.messages.length} messages</span></div><div className="transcript">{session.messages.map((message) => <article key={message.id}><div><strong>{message.role === "participant" ? "Participant" : message.provider ?? "AI assistant"}</strong><span>Turn {String(message.turn).padStart(2, "0")}</span></div><p>{message.content}</p>{message.role === "assistant" && message.requestId && <small>{message.integrationMode ?? "image"} · {message.modelId} · {message.promptVersion} · {message.requestId}{message.finishReason ? ` · ${message.finishReason}` : ""}</small>}</article>)}</div></section><section className="researchSection"><div className="researchSectionTitle"><div><p className="eyebrow">GENERATED MEDIA</p><h2>Image requests and usage</h2></div><span>{session.images.length} / {session.configuredImageTotalLimit ?? 10}</span></div><div className="researchImages">{session.imageRequests.map((request) => <article className="researchImageRequest" key={request.requestId}><div className="researchImageRequestMeta"><strong>{request.status} · {request.requestId}</strong><span>{request.provider ?? "Provider unavailable"} · {request.model ?? "Model unavailable"} · {request.promptVersion}</span><p><b>Participant prompt</b>{request.promptText}</p><p><b>Effective prompt</b>{request.effectivePrompt ?? "Not retained because the request did not complete."}</p><small>{request.completedAt ? new Date(request.completedAt).toLocaleString("en-GB") : new Date(request.createdAt).toLocaleString("en-GB")} · {request.latencyMs ?? "—"} ms{request.errorCode ? ` · ${request.errorCode}` : ""}</small></div><div className="researchImagePair">{request.imageIds.map((imageId) => { const image = session.images.find((item) => item.id === imageId); return image ? <div key={image.id}><ImagePlaceholder image={image} compact /><strong>{image.id}</strong><span>{image.mimeType ?? "Historical mock"}</span><p>Usage: {image.usageTargets?.join(", ") || "Not used"}</p>{image.usageEvents?.map((usage, index) => <small key={`${usage.createdAt}-${index}`}>{usage.action} · {usage.target} · {new Date(usage.createdAt).toLocaleString("en-GB")}</small>)}</div> : null; })}</div></article>)}{!session.imageRequests.length && session.images.map((image) => <article key={image.id}><ImagePlaceholder image={image} compact /><div><strong>{image.id}</strong><span>Historical generated image</span><p>{image.prompt}</p></div></article>)}{!session.images.length && !session.imageRequests.length && <p className="emptyNote">No generated images.</p>}</div></section></div>
    <section className="researchSection submissionSnapshot" id="final-board"><div className="researchSectionTitle"><div><p className="eyebrow">FINAL BOARD RECORD</p><h2>{session.finalSubmission ? "Immutable submission snapshot" : "Current board state"}</h2></div><span>{session.finalSubmission ? session.finalSubmission.id : "Not submitted"}</span></div><div><blockquote>{(session.finalSubmission?.board ?? session.board).concept || "No brand concept recorded."}</blockquote><div className="snapshotPalette">{[["Primary", (session.finalSubmission?.board ?? session.board).primaryColour], ["Secondary 01", (session.finalSubmission?.board ?? session.board).secondaryColour1], ["Secondary 02", (session.finalSubmission?.board ?? session.board).secondaryColour2], ["Accent", (session.finalSubmission?.board ?? session.board).accentColour]].map(([label, value]) => <span key={label} style={{ background: value }}><i>{label}</i><strong>{value}</strong></span>)}</div><p>Logo: {(session.finalSubmission?.board ?? session.board).selectedLogoImageId ?? "Not selected"} · Visual references: {(session.finalSubmission?.board ?? session.board).selectedVisualImageIds.join(", ") || "None selected"}</p><small>{session.finalSubmission ? `${session.finalSubmission.requiredSectionsComplete}/8 required · ${session.finalSubmission.supportingSectionsComplete}/3 supporting · submitted ${new Date(session.finalSubmission.submittedAt).toLocaleString("en-GB")}` : `${boardProgress.requiredComplete}/8 required · ${boardProgress.supportingComplete}/3 supporting`}</small></div></section>
  </main>;
}
