import type { Session } from "@/types";
import { PARTICIPANT_MESSAGE_LIMIT } from "@/data/experiment";

export function TaskGuideContent({ session, compact = false }: { session: Session; compact?: boolean }) {
  return <div className={`taskGuideContent ${compact ? "compact" : ""}`}>
    <section><p className="guideNumber">01</p><div><p className="eyebrow">YOUR TASK</p><h2>Develop one coherent direction for Elsewhere</h2><p>Create an early-stage brand identity direction—not a finished commercial identity. Gradually establish the brand concept, keywords, personality, audience understanding, colour direction, logo or symbol direction, visual references and final rationale. The Working Board is where you organise the direction you intend to submit.</p></div></section>
    <section><p className="guideNumber">02</p><div><p className="eyebrow">SUGGESTED FLOW</p><h2>Move through the task in a clear sequence</h2><ol className="guideFlow"><li>Read the Elsewhere brief</li><li>Complete the Pre-AI Starting Point</li><li>Explore ideas through AI Conversation</li><li>Generate visual references when useful</li><li>Review Generated Visuals</li><li>Organise the chosen direction in the Working Board</li><li>Complete the Final Review</li><li>Complete the questionnaire</li></ol><p>You may move between areas while exploring; you do not need to finish each one before opening another. Use the Working Board to consolidate your final direction.</p></div></section>
    <section><p className="guideNumber">03</p><div><p className="eyebrow">USING AI</p><p>AI Conversation and image generation are tools for exploring possibilities. You can send up to {PARTICIPANT_MESSAGE_LIMIT} text messages during the task. This is a maximum, not a target.</p></div></section>
    <section><p className="guideNumber">04</p><div><p className="eyebrow">GENERATING IMAGES</p><h2>Use the Generate visual control</h2><p>In AI Conversation, write what you want to see in the message box, then click <strong>Generate visual</strong> at the lower-left of the input area instead of sending a normal text-only message. Each successful request creates two images. You have up to five successful requests and ten images in total.</p><p>Images appear in Generated Visuals as references and are not added to the Working Board automatically. You decide whether to use them. Selected images for Logo / symbol direction and Visual style references still need your own written explanation.</p></div></section>
    <section><p className="guideNumber">05</p><div><p className="eyebrow">BEFORE YOU BEGIN</p><ul className="guideGuardrails"><li>Complete all eight required Working Board areas before Final Review submission. Typography, tone of voice, and visual do’s and don’ts are supporting areas.</li><li>The {session.taskDurationMinutes}-minute timer is a guide; reaching it does not close, delete or submit your work.</li><li>Do not imitate an existing brand or trademark, enter personal information, or use discriminatory or stereotyped representations.</li></ul><div className="guideLimits"><div><strong>{session.taskDurationMinutes}</strong><span>minute time guide</span></div><div><strong>{PARTICIPANT_MESSAGE_LIMIT}</strong><span>text messages maximum</span></div><div><strong>{session.configuredImageRequestLimit ?? 5}</strong><span>visual requests</span></div><div><strong>{session.configuredImageTotalLimit ?? 10}</strong><span>images total</span></div></div></div></section>
  </div>;
}
